### ISSUE TITLE
Can you update your plugin to work with livolo zigbee gateway version 2?

### ISSUE THREAD

**Issue by Jar7777** [almsh/homebridge-livolo-switches#3]
Someone HELP :)
need homebridge plugin for livolo zigbee gateway version 2
current version doesn't work! 

records from homebridge start log:

(node:305) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'gatewayId' of undefined
at LivoloApi._reloadSwitchesData (/usr/lib/node_modules/homebridge-livolo-switches/lib/livolo-api.js:154:51)
at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:305) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:305) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Jar7777** [comment]
done with other solution, zigbee2mqtt and Zigbee stick
issue is closed
